server:
  port: 8081
spring:
  application:
    name: SpringSecurityDemo
  datasource:
    #指定数据源类型为Druid
    type: com.alibaba.druid.pool.DruidDataSource
    #连接池配置信息
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springsecurity?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=CTT
    username: root
    password: root
    #连接池配置信息
    druid:
      initial-size: 10 #初始化连接数
      min-idle: 50 #最小连接数
      max-active: 100 #最大连接数
      validation-query: SELECT 1
      max-wait: 60000 # 连接超时等待 60秒
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位毫秒
      time-between-eviction-runs-millis: 60000
#mybaits-plus
#mybaits-plus:
---
server:
  port: 8082
spring:
  application:
    name: SpringSecurityDemo
  profiles: dev
---
server:
  port: 8083
spring:
  application:
    name: SpringSecurityDemo
  profiles: produc