server:
  port: 8081
spring:
  application:
    name: SpringSecurityDemo
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: mysql://127.0.0.1:3306/springsecurity?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=CTT
    data-username: root
    data-password: root
---
server:
  port: 8082
spring:
  application:
    name: SpringSecurityDemo
  profiles: dev
---
server:
  port: 8083
spring:
  application:
    name: SpringSecurityDemo
  profiles: produc